### PR TITLE
feat: Clean up lints

### PR DESCRIPTION
**Pull request by evensolberg**
Ran `cargo clippy -- -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used` and cleaned up most of what it found.

This was a 30-minute cleanup. The remaining stuff takes little digging into the code and should probably be done by the original author.

### CODE REVIEW

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
You're almost done, you just forgot to run `cargo fmt`.

**Comment by GuillaumeGomez** [comment]
Segfault apparently?

**Comment by evensolberg** [comment]
> Segfault apparently?

Yeah, looks like. I'll dig into the code when I can. Not sure why this is happening. 🤷🏻

**Comment by wez** [comment]
The segfault is in the simplemad wrapper when trying to use the Debug impl of its error type:

```
* thread #2, name = 'basic', stop reason = signal SIGSEGV: invalid address (fault address: 0x10)
...
frame #14: 0x00005555555785a8 basic-01690aa0cc075585`_$LT$simplemad..SimplemadError$u20$as$u20$core..fmt..Debug$GT$::fmt::hce2f4e0e9edc5366(self=0x00007ffff7c6f5e0, f=0x00007ffff7c51eb8) at lib.rs:350:10
   347      }
   348  }
   349
-> 350  #[derive(Debug)]
   351  /// An error encountered during the decoding process
   352  pub enum SimplemadError {
   353      /// An `io::Error` generated by the `Reader`
...
(lldb) up
frame #30: 0x000055555556c172 basic-01690aa0cc075585`basic::basic::h2f387ecc94e5047e at basic.rs:12:19
   9    fn basic() {
   10       let meta = mp3_metadata::read_from_file("assets/test.mp3").expect("File error");
   11       let file = File::open("assets/test.mp3").unwrap();
-> 12       let decoder = simplemad::Decoder::decode(file).unwrap();
   13       let mut i = 0;
   14       let mut sum = Duration::new(0, 0);
   15       for decoding_result in decoder {
```

**Comment by wez** [comment]
Stepping through, I'm not sure that it is actually an error. What I suspect is that the simplemad crate is unsafe/unsound and that it is corrupting memory somewhere

**Comment by wez** [comment]
My 2 cents, FWIW, is that simplemad is a dead project and that it isn't worth the time to run down and fix.

I can see from https://github.com/RustAudio/simplemad/pull/32 that there are problems in the upstream library,
and when I tried to reproduce in the upstream just now, the metadata for the crate points to what appears to be the wrong repo with the wrong version of the crate, and the RustAudio org seemingly has the right version but its build script has problems whilst the published does not.

I would advocate removing that dependency from here, but I honestly have no idea what you might replace it with.

However, this PR is not the cause of this crash; you can reproduce it by checking out the default branch in this repo and running `cargo test`.

**Comment by evensolberg** [comment]
Been kinda busy with other things, but I'll look into it and see what I can do. Thanks for submitting that PR. I doubt I'd be able to figure that one out. :)

**Pull request closed without merging**
