### PR TITLE
Update dependencies and fix clippy lints

### PR DESCRIPTION
**Pull request by Elykz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Thanks for the PR! Could you rebase please? I switched to github actions in #28. Your PR should fix the CI.

**Review by GuillaumeGomez — APPROVED** [review]

**Comment by GuillaumeGomez** [comment]
You missed some clippy lints apparently. :)

**Comment by GuillaumeGomez** [comment]
The error comes from a bad migration, seems all good otherwise, thanks!

**Comment by Elykz** [comment]
Cargo nightly was a bit more picky than expected :)

**Comment by GuillaumeGomez** [comment]
It's fine. Thanks for doing this! I merged #29 so your other PR just needs a rebase before running CI again.

**Pull request merged**
